<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>Sample Web API client</AssemblyTitle>
    <Product>Sample Web API Suite</Product>
    <Company>Project ERIC</Company>
    <Copyright>© 2025 Project ERIC. All rights reserved.</Copyright>
    <ApplicationIcon>appicon.ico</ApplicationIcon>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\webspi-suite.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.Staging.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.filenesting.json" Link=".filenesting.json" />
    <None Include="appicon.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApi.Common\WebApi.Common.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(DOTNET_RUNNING_IN_CONTAINER)' != 'true'">
    <Content Include="signing\private.pem">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>