name: webapi-suite

services:
  api-json-loader:
    labels:
      app: loader
      role: api-json-initializer
      purpose: populate-api-json-state
      managed-by: compose
      lifecycle: ephemeral
    image: alpine:latest
    depends_on:
      - api
    command: >
      sh -c "
        set -e
        cp -R /source-data/api-db.json /target-api-data/db.data 2>/dev/null
        chown -R 1654:1654 /target-api-data
      "
    volumes:
      - api-json-data:/target-api-data
      - ../local/data/json:/source-data:ro
    networks:
      - public
    restart: no
