<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyTitle>Sample B2C access token issuer</AssemblyTitle>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApi.Common.Web\WebApi.Common.Web.csproj" />
    <ProjectReference Include="..\WebApi.Common\WebApi.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="runtime\data\" />
    <Folder Include="runtime\secrets\" />
  </ItemGroup>
</Project>