<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>Sample B2C access token issuer</AssemblyTitle>
    <Product>Sample Web API Suite</Product>
    <Company>Project ERIC</Company>
    <Copyright>© 2025 Project ERIC. All rights reserved.</Copyright>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\webspi-suite.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApi.Common.Web\WebApi.Common.Web.csproj" />
    <ProjectReference Include="..\WebApi.Common\WebApi.Common.csproj" />
  </ItemGroup>
</Project>