<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Shared Web components for sample Web API projects</AssemblyTitle>
    <Product>Sample Web API Suite</Product>
    <Company>Project ERIC</Company>
    <Copyright>© 2025 Project ERIC. All rights reserved.</Copyright>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\webspi-suite.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApi.Common\WebApi.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
