name: webapi-suite

services:

  issuer-postgres-loader:
    image: alpine:latest
    depends_on:
      postgres-issuer:
        condition: service_healthy
    command: >
      sh -c "
        set -e
        apk update && apk add --no-cache postgresql-client
        /provisioning/provision.sh ISSUER --host=issuerdb.webapisuite.projecteric.io --bootstrap-user=db_manager --bootstrap-password-file=/provisioning/db-manager-password.txt
      "
    volumes:
      - ../local/data/postgres:/provisioning:ro
    networks:
      - public
    restart: no
