using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//     Template: EntityType.t4
//     Generated at: 2026-01-17 11:02:38 UTC
// </auto-generated>
// ------------------------------------------------------------------------------

namespace WebApi.Issuer.DataAccess.Entity;

[System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1852", Justification = "Generated by T4")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812", Justification = "Instantiated by DI container")]
internal partial class ClientService
{
    public Guid Id { get; set; }

    public Guid ClientId { get; set; }

    public Guid ServiceId { get; set; }

    public Guid KeyId { get; set; }

    public virtual Client Client { get; set; } = null!;

    public virtual ICollection<ClientServiceScope> ClientServiceScopes { get; set; } = new List<ClientServiceScope>();

    public virtual Key Key { get; set; } = null!;

    public virtual Service Service { get; set; } = null!;
}
