using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//     Template: EntityType.t4
//     Generated at: 2026-01-26 06:28:04 UTC
// </auto-generated>
// ------------------------------------------------------------------------------

namespace WebApi.Issuer.DataAccess.Entity;

[System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1852", Justification = "Generated by T4")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812", Justification = "Instantiated by DI container")]
internal partial class ClientServiceScope
{
    public Guid Id { get; set; }

    public Guid ClientServiceId { get; set; }

    public string Scope { get; set; } = null!;

    public virtual ClientService ClientService { get; set; } = null!;
}
