using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//     Template: EntityType.t4
//     Generated at: 2026-01-17 11:02:25 UTC
// </auto-generated>
// ------------------------------------------------------------------------------

namespace WebApi.Service.DataAccess.Entity;

[System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1852", Justification = "Generated by T4")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812", Justification = "Instantiated by DI container")]
internal partial class Game
{
    public Guid Id { get; set; }

    public string Type { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string PlayerName { get; set; } = null!;

    public int PlayerHealth { get; set; }

    public virtual ICollection<Relation> Relations { get; set; } = new List<Relation>();
}
