<Project>
  <!-- Include all runtime -->
  <ItemGroup Condition="Exists('$(SecretStoreRoot)')">
    <AssetFiles Include="$(SecretStoreRoot)/**/*">
      <Link>secrets\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </AssetFiles>
  </ItemGroup>
  <ItemGroup Condition="Exists('$(DataStoreRoot)')">
    <AssetFiles Include="$(DataStoreRoot)/**/*">
      <Link>data\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </AssetFiles>
  </ItemGroup>
  <ItemGroup>
    <None Update="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Exclude container folders -->
  <ItemGroup>
    <ExcludedAssetDirs Include="$(SecretStoreRoot)" Condition="'$(IsContainerBuild)'=='true'" />
    <ExcludedAssetDirs Include="$(DataStoreRoot)" Condition="'$(IsContainerBuild)'=='true'" />
    <AssetFiles Remove="@(ExcludedAssetDirs->'%(FullPath)/**/*')" Condition="'@(ExcludedAssetDirs)' != ''" />
  </ItemGroup>

  <!-- Copy runtime for normal build -->
  <Target Name="CopyRuntimeAfterBuild" AfterTargets="Build" Condition="'@(AssetFiles)' != ''">
    <PropertyGroup>
      <AssetTargetDir>$(OutDir)runtime</AssetTargetDir>
    </PropertyGroup>
    <Copy SourceFiles="@(AssetFiles)" DestinationFiles="@(AssetFiles->'$(OutDir)runtime\%(Link)')" SkipUnchangedFiles="true" />
  </Target>

  <!-- Copy runtime for publish -->
  <Target Name="CopyRuntimeAfterPublish" AfterTargets="Publish" Condition="'@(AssetFiles)' != ''">
    <PropertyGroup>
      <AssetTargetDir>$(PublishDir)runtime</AssetTargetDir>
    </PropertyGroup>
    <Copy SourceFiles="@(AssetFiles)" DestinationFolder="$(AssetTargetDir)\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>