name: webapi-suite
services:
  issuer:
    labels:
      - "tier=backend"
      - "purpose=authentication and authorization server"
    build:
      context: .
      dockerfile: ./WebApi.Issuer/Dockerfile
    image: webapi-suite/issuer:latest
    ports:
      - "5001:5001"
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/cert.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/https/key.pem
      - ISSUER_BASE_URL=https://issuer:5001/connect
      - TOKEN_LIFETIME_MINUTES=30
      - Logging__LogLevel__Default=Warning
      - Logging__Console__FormatterOptions__TimestampFormat="yyyy-MM-dd HH:mm:ss:fff"

    volumes:
      - ./WebApi.Issuer/signing:/app/signing:ro
      - ./WebApi.Issuer/https:/app/https:ro
      - ./WebApi.Issuer/data:/app/data:rw
    networks:
      - public
  api:
    labels:
      - "tier=backend"
      - "purpose=protected Web API service"
    build:
      context: .
      dockerfile: ./WebApi.Service/Dockerfile
    image: webapi-suite/api:latest
    ports:
      - "5002:5002"
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/cert.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/https/key.pem
      - ISSUER_BASE_URL=https://issuer:5001/connect
      - API_ID=af2157c0-3280-42e7-b327-33e5aa3ec76e
      - Logging__LogLevel__Default=Warning
      - Logging__Console__FormatterOptions__TimestampFormat="yyyy-MM-dd HH:mm:ss:fff"

    volumes:
      - ./WebApi.Service/https:/app/https:ro
      - ./WebApi.Service/data:/app/data:rw
    networks:
      - public
    depends_on:
      - issuer
  client:
    labels:
      - "tier=frontend"
      - "purpose=client application consuming the Web API"
    build:
      context: .
      dockerfile: ./WebApi.Client/Dockerfile
    image: webapi-suite/client:latest
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ISSUER_BASE_URL=https://issuer:5001/connect
      - API_BASE_URL=https://api:5002
      - CLIENT_ID=088f6a2e-8f00-4340-b32d-49de4acde03c
      - API_ID=af2157c0-3280-42e7-b327-33e5aa3ec76e
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Error
      - Logging__LogLevel__System=Error
      - Logging__Console__FormatterOptions__TimestampFormat="yyyy-MM-dd HH:mm:ss:fff"

    volumes:
      - ./WebApi.Client/signing:/app/signing:ro
      - ./WebApi.Client/https:/app/https:ro
    networks:
      - public
    depends_on:
      - issuer
      - api
networks:
  public:
    labels:
      - "purpose=publicly accessible network for the suite of Web API services"
    driver: bridge
